// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wftcnwdqeqdtcjsmzixy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmdGNud2RxZXFkdGNqc216aXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTE4MDgsImV4cCI6MjA2Mjk4NzgwOH0.LCoNNCD7drih5zJ-8ylVUrH-hIo0cSRZGpX0I7L4Czg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);